/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import BUS.ChiTietChuongTrinhGiamGiaBUS;
import DAO.ChiTietChuongTrinhGiamGiaDAO;
import BUS.ChuongTrinhGiamGiaBUS;
import BUS.LoaiSPBUS;
import BUS.NhanVienBUS;
import DTO.ChuongTrinhGiamGiaDTO;
import DAO.ChuongTrinhGiamGiaDAO;
import DTO.ChiTietChuongTrinhGiamGiaDTO;
import DTO.LoaiSanPhamDTO;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author anhhu
 */
public class CTCTGG_user extends javax.swing.JPanel {

    /**
     * Creates new form CTCTGG
     */
    public CTCTGG_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formCTGG_txt = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        timkiem_form = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        them_btn29 = new javax.swing.JButton();
        label_SL = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        opt_txt = new javax.swing.JComboBox<>();
        tim_panel = new javax.swing.JPanel();
        tim_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CTGG_table = new javax.swing.JTable();

        formCTGG_txt.setBackground(new java.awt.Color(0, 255, 255));
        formCTGG_txt.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel51.setText("Chi tiết giảm giá");
        jLabel51.setPreferredSize(new java.awt.Dimension(191, 20));

        timkiem_form.setBackground(new java.awt.Color(0, 255, 255));
        timkiem_form.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(153, 255, 255))));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel52.setText("Tìm Kiếm");

        them_btn29.setBackground(new java.awt.Color(38, 170, 226));
        them_btn29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn29.setForeground(new java.awt.Color(255, 255, 255));
        them_btn29.setText("     Enter");
        them_btn29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn29.setIconTextGap(2);
        them_btn29.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn29.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn29.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them_btn29them_btn2MouseClicked(evt);
            }
        });
        them_btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn29them_btn2ThongkebtnActionPerformed(evt);
            }
        });

        label_SL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_SL.setForeground(new java.awt.Color(255, 51, 51));

        jPanel25.setLayout(new java.awt.CardLayout());

        opt_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID chương trình", "ID sản phẩm","Số tiền giảm",}));

        tim_panel.setLayout(new java.awt.CardLayout());

        tim_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_txttim_txtActionPerformed(evt);
            }
        });
        tim_panel.add(tim_txt, "card2");

        javax.swing.GroupLayout timkiem_formLayout = new javax.swing.GroupLayout(timkiem_form);
        timkiem_form.setLayout(timkiem_formLayout);
        timkiem_formLayout.setHorizontalGroup(
            timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiem_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timkiem_formLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(them_btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_SL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(timkiem_formLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(opt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(tim_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timkiem_formLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        timkiem_formLayout.setVerticalGroup(
            timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiem_formLayout.createSequentialGroup()
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(timkiem_formLayout.createSequentialGroup()
                        .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tim_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(timkiem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(them_btn29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        //doc_data();

        // Tạo một lớp con kế thừa từ DefaultTableModel
        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID chương trình ", "Id sản phẩm","Loại giảm", "Số tiền giảm", "%giảm"
            }
        ) {
            // Ghi đè phương thức isCellEditable để ngăn chặn việc chỉnh sửa ô
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Ngăn chặn việc chỉnh sửa ô
            }
        };
        CTGG_table.setModel(model
        );
        jScrollPane2.setViewportView(CTGG_table);
        doc_data();

        javax.swing.GroupLayout formCTGG_txtLayout = new javax.swing.GroupLayout(formCTGG_txt);
        formCTGG_txt.setLayout(formCTGG_txtLayout);
        formCTGG_txtLayout.setHorizontalGroup(
            formCTGG_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(formCTGG_txtLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(timkiem_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formCTGG_txtLayout.setVerticalGroup(
            formCTGG_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCTGG_txtLayout.createSequentialGroup()
                .addGroup(formCTGG_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timkiem_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formCTGG_txtLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formCTGG_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formCTGG_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void them_btn29them_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn29them_btn2MouseClicked

 
            Table_ghi t = new Table_ghi();
            if(tim_txt.getText().equals("")){
                doc_data();
            }
            else{
                ArrayList<ChiTietChuongTrinhGiamGiaDTO> arr = new ArrayList<>();
                ChiTietChuongTrinhGiamGiaBUS NVB = new ChiTietChuongTrinhGiamGiaBUS();
                try {
                    NVB.docDSChiTietCTGG();
                } catch (SQLException ex) {
                    Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
                }
                String opt = (String) opt_txt.getSelectedItem();
                switch (opt) {
                    case "ID chương trình" -> {
                        arr = NVB.timkiem_mang(opt,Integer.parseInt(tim_txt.getText()));
                        if(arr.isEmpty()){
                            doc_data();
                        }
                        else{
                            DefaultTableModel model  = (DefaultTableModel) CTGG_table.getModel();
                            model.setRowCount(0); //xóa bảng

                            for(ChiTietChuongTrinhGiamGiaDTO x : arr){
       boolean flag = false;
       ChuongTrinhGiamGiaBUS CTB = new ChuongTrinhGiamGiaBUS();
                                try {
                                    CTB.docDSCTGG();
                                } catch (SQLException ex) {
                                    Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
                                }
       for(ChuongTrinhGiamGiaDTO k : CTB.dsctgg){
           if(k.getIdChuongTrinh() == x.getIdChuongTrinh()){
               flag = t.isDateValid(k.getStart(),k.getEnd());
           }
       }
                                if (flag) {
           try {
               t.addRowToTable(x.getIdChuongTrinh(), x.getIdSanPham(),t.doc_loai_sp(x.getLoaiGiam()), x.getSoTienGiam(), x.getPhanTramGiam());
           } catch (SQLException ex) {
               Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
           }
                                }
                            }

                        }
                    }
                    case "ID sản phẩm" -> {

                         arr = NVB.timkiem_mang(opt,Integer.parseInt(tim_txt.getText()));
                        if(arr.isEmpty()){
                            doc_data();
                        }
                        else{
                            DefaultTableModel model  = (DefaultTableModel) CTGG_table.getModel();
                            model.setRowCount(0); //xóa bảng

                            for(ChiTietChuongTrinhGiamGiaDTO x : arr){
       boolean flag = false;
       ChuongTrinhGiamGiaBUS CTB = new ChuongTrinhGiamGiaBUS();
                                try {
                                    CTB.docDSCTGG();
                                } catch (SQLException ex) {
                                    Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
                                }
       for(ChuongTrinhGiamGiaDTO k : CTB.dsctgg){
           if(k.getIdChuongTrinh() == x.getIdChuongTrinh()){
               flag = t.isDateValid(k.getStart(),k.getEnd());
           }
       }
                                if (flag) {
           try {
               t.addRowToTable(x.getIdChuongTrinh(), x.getIdSanPham(),t.doc_loai_sp(x.getLoaiGiam()), x.getSoTienGiam(), x.getPhanTramGiam());
           } catch (SQLException ex) {
               Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
           }
                                }
                            }

                        }
                    }

                                        case "Số tiền giảm" -> {

                           arr = NVB.timkiem_mang(opt,Integer.parseInt(tim_txt.getText()));
                        if(arr.isEmpty()){
                            doc_data();
                        }
                        else{
                            DefaultTableModel model  = (DefaultTableModel) CTGG_table.getModel();
                            model.setRowCount(0); //xóa bảng

                            for(ChiTietChuongTrinhGiamGiaDTO x : arr){
       boolean flag = false;
       ChuongTrinhGiamGiaBUS CTB = new ChuongTrinhGiamGiaBUS();
                                try {
                                    CTB.docDSCTGG();
                                } catch (SQLException ex) {
                                    Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
                                }
       for(ChuongTrinhGiamGiaDTO k : CTB.dsctgg){
           if(k.getIdChuongTrinh() == x.getIdChuongTrinh()){
               flag = t.isDateValid(k.getStart(),k.getEnd());
           }
       }
                                if (flag) {
           try {
               t.addRowToTable(x.getIdChuongTrinh(), x.getIdSanPham(),t.doc_loai_sp(x.getLoaiGiam()), x.getSoTienGiam(), x.getPhanTramGiam());
           } catch (SQLException ex) {
               Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
           }
                                }
                            }

                        }
                    }
                                        
                                

                    default -> {
                    }
                }
            }
           

     
    }//GEN-LAST:event_them_btn29them_btn2MouseClicked

    private void them_btn29them_btn2ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn29them_btn2ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn29them_btn2ThongkebtnActionPerformed

    private void tim_txttim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_txttim_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tim_txttim_txtActionPerformed

    private void them_btn30them_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn30them_btn2MouseClicked
        try {
            int ID_CT = getSelectedRow(CTGG_table)[0];
            int ID_SP = getSelectedRow(CTGG_table)[1];
            System.out.print(ID_CT +" "+ID_SP);
            if(ID_SP == -1){
            JOptionPane.showMessageDialog(null,"Hãy chọn 1 dòng để xóa!","Lỗi",JOptionPane.ERROR_MESSAGE);
            } 
            else if(!check_CTGG(ID_CT)){
            JOptionPane.showMessageDialog(null,"Một chương trình phải có ít nhất 1 chi tiết!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
            else{
            ChiTietChuongTrinhGiamGiaBUS CTGGBUS = new ChiTietChuongTrinhGiamGiaBUS();
            CTGGBUS.docDSChiTietCTGG();
            CTGGBUS.xoa(ID_CT,ID_SP);
            doc_data();
            }
        } catch (SQLException ex) {
            Logger.getLogger(CTCTGG_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_them_btn30them_btn2MouseClicked

    private void them_btn30them_btn2ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn30them_btn2ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn30them_btn2ThongkebtnActionPerformed

    private void them_btn31them_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn31them_btn2MouseClicked
    
        
        
    }//GEN-LAST:event_them_btn31them_btn2MouseClicked

    private void them_btn31them_btn2ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn31them_btn2ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn31them_btn2ThongkebtnActionPerformed

    private void tiengiam_txttim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiengiam_txttim_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiengiam_txttim_txtActionPerformed

    private void ptgg_txttim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptgg_txttim_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptgg_txttim_txtActionPerformed

        
            public class Table_ghi {
    public Table_ghi(){};
    // Phương thức thêm dòng vào bảng
    
       private void addRowToTable(int id_CT, int id_SP, String loai, int tien, int pt_giam) {
javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) CTGG_table.getModel();
Object[] rowData = {id_CT, id_SP,loai, tien, pt_giam};
        model.addRow(rowData);
    }
       


    public  boolean isDateValid(String startDateStr, String endDateStr) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            LocalDate startDate = LocalDate.parse(startDateStr, formatter);
            LocalDate endDate = LocalDate.parse(endDateStr, formatter);
            LocalDate today = LocalDate.now();

            // Kiểm tra nếu hôm nay chưa quá hạn
            return !today.isAfter(endDate);

        } catch (DateTimeParseException e) {
            // Xử lý lỗi nếu ngày không hợp lệ
            e.printStackTrace();
            return false;
        }
    }

         
      public String doc_loai_sp(int id) throws SQLException{
      LoaiSPBUS LoaiBUS = new LoaiSPBUS();
       LoaiBUS.doc();
       for(LoaiSanPhamDTO x : LoaiBUS.DSSP){
       if(id == x.getIdLoaiSP()){
       return x.getTenLoaiSP();
       }
       }
       return null;
      }
      
         public int doc_id_loai_sp(String str) throws SQLException{
      LoaiSPBUS LoaiBUS = new LoaiSPBUS();
       LoaiBUS.doc();
       for(LoaiSanPhamDTO x : LoaiBUS.DSSP){
       if(str.equals(x.getTenLoaiSP())){
       return x.getIdLoaiSP();
       }
       }
       return -1;
      }
      
                      
                            
         public boolean isPositiveNumber(String str) {
        try {
            // Chuyển chuỗi thành số thực
            double number = Double.parseDouble(str);
            // Kiểm tra nếu số này là số dương
            return number >= 0;
        } catch (NumberFormatException e) {
            // Nếu chuỗi không thể chuyển thành số, trả về false
            return false;
        }
    }
       
    
                     
    }

                
    public void doc_data(){

try {
    int SL_HC = 0;
    ChiTietChuongTrinhGiamGiaBUS NVB = new ChiTietChuongTrinhGiamGiaBUS();
    NVB.docDSChiTietCTGG();
    DefaultTableModel model  = (DefaultTableModel) CTGG_table.getModel();
    model.setRowCount(0); //xóa bảng        
       Table_ghi t = new Table_ghi();
        for (ChiTietChuongTrinhGiamGiaDTO x : NVB.danhSachChiTietCTGG) {
           
       boolean flag = false;
       ChuongTrinhGiamGiaBUS CTB = new ChuongTrinhGiamGiaBUS();
       CTB.docDSCTGG();
       for(ChuongTrinhGiamGiaDTO k : CTB.dsctgg){
           if(k.getIdChuongTrinh() == x.getIdChuongTrinh()){
               flag = t.isDateValid(k.getStart(),k.getEnd());
           }
       }
            
                if(flag){
                SL_HC++;
                   t.addRowToTable(x.getIdChuongTrinh(), x.getIdSanPham(),t.doc_loai_sp(x.getLoaiGiam()), x.getSoTienGiam(), x.getPhanTramGiam());
                }            
        }
        label_SL.setText(SL_HC + " chi tiết");
    } catch (SQLException e) {
        System.out.println("Lỗi khi thao tác với cơ sở dữ liệu: " + e.getMessage());
    }
}

//hàm lấy ra id của dòng dc chọn
public int[] getSelectedRow(JTable table) throws SQLException {
    int selectedRow = table.getSelectedRow();
    Table_ghi t = new Table_ghi();
    if (selectedRow != -1) {
        int data[] = new int[3];  // Khởi tạo mảng với kích thước 2
        try {
            int id = (int) table.getValueAt(selectedRow, 0);
            int id_SP = (int) table.getValueAt(selectedRow, 1);
            int loai  = t.doc_id_loai_sp((String) table.getValueAt(selectedRow, 2));
            System.out.print(id + " " + id_SP);
            data[0] = id;
            data[1] = id_SP;
            data[2] = loai;
        } catch (ClassCastException e) {
            // Xử lý trường hợp giá trị không phải là kiểu int
            throw new SQLException("The data in the table is not of type int", e);
        }
        return data;
    } else {
                int data[] = new int[3];  // Khởi tạo mảng với kích thước 2
            data[0] = -1;
            data[1] = -1;
            data[2] = -1;
        return data;
    }
}

    
public boolean check_CTGG(int ID_CT) throws SQLException{
     
    ChiTietChuongTrinhGiamGiaBUS CTCTGG = new ChiTietChuongTrinhGiamGiaBUS();
    CTCTGG.docDSChiTietCTGG();
    ArrayList<ChiTietChuongTrinhGiamGiaDTO> data = new ArrayList<>();
    for(ChiTietChuongTrinhGiamGiaDTO k : CTCTGG.danhSachChiTietCTGG){
    if(k.getIdChuongTrinh() == ID_CT){
    data.add(k);
    }
    }
    
    if(data.size() == 1) { return false; }
    else return true;
}
        public static void main(String args[]) {


    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JFrame j = new JFrame();
        
            j.add(new CTCTGG_user());
            j.setSize(780, 600);
            j.setVisible(true);
        }
    });
    

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable CTGG_table;
    private static javax.swing.JPanel formCTGG_txt;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel label_SL;
    private static javax.swing.JComboBox<String> opt_txt;
    private javax.swing.JButton them_btn29;
    private javax.swing.JPanel tim_panel;
    private javax.swing.JTextField tim_txt;
    private javax.swing.JPanel timkiem_form;
    // End of variables declaration//GEN-END:variables
}
