/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import BUS.ChiTietChuongTrinhGiamGiaBUS;
import BUS.ChuongTrinhGiamGiaBUS;
import BUS.LoaiSPBUS;
import BUS.NhanVienBUS;
import BUS.SanPhamBUS;
import DTO.ChiTietChuongTrinhGiamGiaDTO;
import DTO.LoaiSanPhamDTO;
import DTO.SanPhamDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhhu
 */
public class form_them_CTGG extends javax.swing.JPanel {

       private int id_SP_giam;
       private String loai_SP_giam;
        DefaultTableModel model1;

    /**
     * Creates new form form_them_CTGG
     */
    public form_them_CTGG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ptgiam_txt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tien_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        them_btn6 = new javax.swing.JButton();
        ptgg_txt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tt = new javax.swing.JScrollPane();
        NhanVienBUS NV = new NhanVienBUS();
        SP_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CTGG_table = new javax.swing.JTable();
        them_btn7 = new javax.swing.JButton();
        them_btn8 = new javax.swing.JButton();
        them_btn9 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        ptgiam_txt.setBackground(new java.awt.Color(255, 255, 255));
        ptgiam_txt.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thêm Chi Tiết Chương Trình");
        jLabel1.setPreferredSize(new java.awt.Dimension(191, 20));

        tien_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tien_txtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Số tiền giảm: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("% giảm:");

        them_btn6.setBackground(new java.awt.Color(102, 255, 102));
        them_btn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn6.setForeground(new java.awt.Color(255, 255, 255));
        them_btn6.setText("    Xác nhận");
        them_btn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn6.setIconTextGap(2);
        them_btn6.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn6.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn6.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them_btn6MouseClicked(evt);
            }
        });
        them_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn6ThongkebtnActionPerformed(evt);
            }
        });

        ptgg_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptgg_txtActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        // Tạo một lớp con kế thừa từ DefaultTableModel
        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên","Đơn giá", "Loại"
            }
        ) {
            // Ghi đè phương thức isCellEditable để ngăn chặn việc chỉnh sửa ô
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Ngăn chặn việc chỉnh sửa ô
            }
        };
        SP_table.setModel(model
        );
        SP_table.setGridColor(new java.awt.Color(102, 255, 255));
        SP_table.setSelectionBackground(new java.awt.Color(102, 255, 255));
        SP_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SP_tableMouseClicked(evt);
            }
        });
        tt.setViewportView(SP_table);
        doc_data_sp();

        SP_table.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = SP_table.getSelectedRow();
                if (selectedRow != -1) {

                    // Lấy giá trị của cột ID từ hàng được chọn
                    int id = (int) SP_table.getValueAt(selectedRow, 0);
                    String loai = (String) SP_table.getValueAt(selectedRow, 3);

                    id_SP_giam = id;
                    loai_SP_giam = loai;

                    System.out.print(id_SP_giam + " " + loai_SP_giam);
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("                             Danh sách sản phẩm");

        // Tạo một lớp con kế thừa từ DefaultTableModel
        model1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SP", "Loại giảm", "Số tiền giảm", "% giảm"
            }
        ) {
            // Ghi đè phương thức isCellEditable để ngăn chặn việc chỉnh sửa ô
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Ngăn chặn việc chỉnh sửa ô
            }
        };
        CTGG_table.setModel(model1

        );
        jScrollPane1.setViewportView(CTGG_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        them_btn7.setBackground(new java.awt.Color(38, 170, 226));
        them_btn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn7.setForeground(new java.awt.Color(255, 255, 255));
        them_btn7.setText("   Thêm");
        them_btn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn7.setIconTextGap(2);
        them_btn7.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn7.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn7.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them_btn7MouseClicked(evt);
            }
        });
        them_btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn7ThongkebtnActionPerformed(evt);
            }
        });

        them_btn8.setBackground(new java.awt.Color(204, 204, 255));
        them_btn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn8.setForeground(new java.awt.Color(255, 255, 255));
        them_btn8.setText("Hoàn tác");
        them_btn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn8.setIconTextGap(2);
        them_btn8.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn8.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn8.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them_btn8MouseClicked(evt);
            }
        });
        them_btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn8ThongkebtnActionPerformed(evt);
            }
        });

        them_btn9.setBackground(new java.awt.Color(255, 51, 51));
        them_btn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them_btn9.setForeground(new java.awt.Color(255, 255, 255));
        them_btn9.setText("    Xóa");
        them_btn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        them_btn9.setIconTextGap(2);
        them_btn9.setMaximumSize(new java.awt.Dimension(132, 32));
        them_btn9.setMinimumSize(new java.awt.Dimension(120, 30));
        them_btn9.setPreferredSize(new java.awt.Dimension(132, 40));
        them_btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them_btn9MouseClicked(evt);
            }
        });
        them_btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btn9ThongkebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ptgiam_txtLayout = new javax.swing.GroupLayout(ptgiam_txt);
        ptgiam_txt.setLayout(ptgiam_txtLayout);
        ptgiam_txtLayout.setHorizontalGroup(
            ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptgiam_txtLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(ptgiam_txtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptgg_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptgiam_txtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptgiam_txtLayout.createSequentialGroup()
                        .addComponent(them_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(them_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(them_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptgiam_txtLayout.createSequentialGroup()
                        .addComponent(them_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
            .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ptgiam_txtLayout.setVerticalGroup(
            ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptgiam_txtLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ptgg_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(them_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptgiam_txtLayout.createSequentialGroup()
                    .addContainerGap(269, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(291, Short.MAX_VALUE)))
            .addGroup(ptgiam_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptgiam_txtLayout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ptgiam_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ptgiam_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 285, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 286, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void them_btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn6MouseClicked
        int SL = (int) model1.getRowCount();
        ChuongTrinhGiamGiaBUS CTGGB = new ChuongTrinhGiamGiaBUS();
        Table_ghi t = new Table_ghi();
        int flag1 = 0;
           try {
               CTGGB.docDSCTGG();
           } catch (SQLException ex) {
               Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
           }
        
         int ID_CTGG = (int)CTGGB.dsctgg.get(CTGGB.dsctgg.size() - 1).getIdChuongTrinh();
         
        if(SL == 0){
               JOptionPane.showMessageDialog(null,"Chưa có chi tiết nào","Lỗi",JOptionPane.ERROR_MESSAGE);   
        }
        else{
        ChiTietChuongTrinhGiamGiaBUS CTCTGG = new ChiTietChuongTrinhGiamGiaBUS();
        ChiTietChuongTrinhGiamGiaDTO x = new ChiTietChuongTrinhGiamGiaDTO();
            try {
                CTCTGG.docDSChiTietCTGG();
            } catch (SQLException ex) {
                Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        for(int i = 0; i < SL; i++){
        int ID_SP = (int)model1.getValueAt(i, 0);
        int loai = 0;
            try {
                loai  = t.doc_id_loai_sp((String) model1.getValueAt(i, 1));
            } catch (SQLException ex) {
                Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
            }
        int tien_giam = (int)model1.getValueAt(i, 2);
       // Lấy giá trị từ cell
String cellValue = (String) model1.getValueAt(i, 3);
// Tách phần trăm từ chuỗi và chuyển đổi thành số nguyên
int percentValue = Integer.parseInt(cellValue.split("%")[0]);

   x.setIdChuongTrinh(ID_CTGG);
   x.setIdSanPham(ID_SP);
   x.setLoaiGiam(loai);
   x.setPhanTramGiam(percentValue);
   x.setSoTienGiam(tien_giam);
   
   boolean flag = true;
   
   for(ChiTietChuongTrinhGiamGiaDTO k : CTCTGG.danhSachChiTietCTGG){
   if(x.getIdChuongTrinh() == k.getIdChuongTrinh() && x.getIdSanPham() == k.getIdSanPham()){
       flag = false; break;
   }
   }
   
   if(!flag){
          JOptionPane.showMessageDialog(null,"Có chi tiết đã được thêm vào rồi","Lỗi",JOptionPane.ERROR_MESSAGE);
          break;
   }
   else{
            try {
                flag1++;
                CTCTGG.them(x);
            } catch (SQLException ex) {
                Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
            } 
   }
           
        }
        if(flag1 != 0){
                 JOptionPane.showMessageDialog(this,"Thêm chi tiết thành công");
        }
        }
    }//GEN-LAST:event_them_btn6MouseClicked

    private void them_btn6ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn6ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn6ThongkebtnActionPerformed

    private void ptgg_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptgg_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptgg_txtActionPerformed

    private void SP_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SP_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SP_tableMouseClicked

    private void them_btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn7MouseClicked
       Table_ghi t = new Table_ghi();
       String tien = tien_txt.getText();
       String pt_giam = ptgg_txt.getText();
       int click = 0;
           try {
               click = getSelectedRowID(SP_table);
           } catch (SQLException ex) {
               Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
           }
       if(pt_giam.equals("") || tien.equals("")){
       JOptionPane.showMessageDialog(null,"xin hãy nhập đầy đủ thông tin cần giảm giá","Lỗi",JOptionPane.ERROR_MESSAGE);
       }
       else if(click == -1){
       JOptionPane.showMessageDialog(null,"Hãy chọn sản phẩm muốn áp dụng chương trình","Lỗi",JOptionPane.ERROR_MESSAGE);          
       }
       else if(!t.isPositiveNumber(tien) || !t.isPositiveNumber(pt_giam)){
       JOptionPane.showMessageDialog(null,"Thông tin không hợp lệ","Lỗi",JOptionPane.ERROR_MESSAGE);   
       }
       else{
           boolean check = true;
        int rowCount = model1.getRowCount();
        int columnCount = model1.getColumnCount();
        
        for (int row = 0; row < rowCount; row++) {
                // Lấy dữ liệu của ô hiện tại
                int ID_SP = (int) model1.getValueAt(row, 0);
                if(id_SP_giam == ID_SP){ check = false; break; }
        }
        
        if(!check){
               JOptionPane.showMessageDialog(null,"Đã thêm sản phẩm này rồi","Lỗi",JOptionPane.ERROR_MESSAGE);   
        }
        else{
       t.addRowToTable_ctgg(id_SP_giam, loai_SP_giam, Integer.parseInt(tien) , pt_giam + "%");
        }
       }
    }//GEN-LAST:event_them_btn7MouseClicked

    private void them_btn7ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn7ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn7ThongkebtnActionPerformed

    private void them_btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn8MouseClicked
        tien_txt.setText("");
        ptgg_txt.setText("");
        model1.setRowCount(0); //xóa bảng        

    }//GEN-LAST:event_them_btn8MouseClicked

    private void them_btn8ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn8ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn8ThongkebtnActionPerformed

    private void them_btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_btn9MouseClicked
                   int click = 0;
        try {
                click = getSelectedRowIndex(CTGG_table);
           } catch (SQLException ex) {
               Logger.getLogger(form_them_CTGG.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           if(click == -1){
                  JOptionPane.showMessageDialog(null,"Hãy chọn dòng muốn xóa","Lỗi",JOptionPane.ERROR_MESSAGE);   
           }
           else{
           model1.removeRow(click);
           }
        
    }//GEN-LAST:event_them_btn9MouseClicked

    private void them_btn9ThongkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btn9ThongkebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them_btn9ThongkebtnActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tien_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tien_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tien_txtActionPerformed

    
        public void doc_data_sp(){

try {
    SanPhamBUS NVB = new SanPhamBUS();
    NVB.docDSSP();
    DefaultTableModel model  = (DefaultTableModel) SP_table.getModel();
    model.setRowCount(0); //xóa bảng        
       Table_ghi t = new Table_ghi();
        for (SanPhamDTO x : NVB.dssp) {
                if(x.getSoLuongSpConLai() > 0){
                   t.addRowToTable_sp(x.getIdSP(),x.getTenSP(), x.getDonGia(), t.doc_loai_sp(x.getIdLoaiSP()));
                }            
        }
    } catch (SQLException e) {
        System.out.println("Lỗi khi thao tác với cơ sở dữ liệu: " + e.getMessage());
    }
}
        
            public static class Table_ghi {
    public Table_ghi(){};
    // Phương thức thêm dòng vào bảng
       private void addRowToTable_sp(int id, String ten, int gia, String loai) {
javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) SP_table.getModel();
Object[] rowData = {id, ten, gia, loai};
        model.addRow(rowData);
    }
       
              private void addRowToTable_ctgg(int id, String loai, int tien, String pt_giam) {
javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) CTGG_table.getModel();
Object[] rowData = {id, loai, tien, pt_giam};
        model.addRow(rowData);
    }
     
      public String doc_loai_sp(int id) throws SQLException{
      LoaiSPBUS LoaiBUS = new LoaiSPBUS();
       LoaiBUS.doc();
       for(LoaiSanPhamDTO x : LoaiBUS.DSSP){
       if(id == x.getIdLoaiSP()){
       return x.getTenLoaiSP();
       }
       }
       return null;
      }
      
            public int doc_id_loai_sp(String str) throws SQLException{
      LoaiSPBUS LoaiBUS = new LoaiSPBUS();
       LoaiBUS.doc();
       for(LoaiSanPhamDTO x : LoaiBUS.DSSP){
       if(str.equals(x.getTenLoaiSP())){
       return x.getIdLoaiSP();
       }
       }
       return -1;
      }
      
      
         public boolean isPositiveNumber(String str) {
        try {
            // Chuyển chuỗi thành số thực
            double number = Double.parseDouble(str);
            // Kiểm tra nếu số này là số dương
            return number >= 0;
        } catch (NumberFormatException e) {
            // Nếu chuỗi không thể chuyển thành số, trả về false
            return false;
        }
    }
         
    }
    
public static void main(String args[]) {

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JFrame j = new JFrame();
     
            j.add(new form_them_CTGG());
            j.setSize(780, 600);
            j.setVisible(true);
        }
    });
}

//hàm lấy ra id của dòng dc chọn
public int getSelectedRowID(JTable table) throws SQLException{
    int selectedRow = table.getSelectedRow();
    if(selectedRow != -1){
        int id = (int) table.getValueAt(selectedRow, 0);
            return id; // Cột "ID" là cột đầu tiên (index 0)
    }
    else{
        return -1;
    }
}

public int getSelectedRowIndex(JTable table) throws SQLException{
    int selectedRow = table.getSelectedRow();
    if(selectedRow != -1){
            return selectedRow; // Cột "ID" là cột đầu tiên (index 0)
    }
    else{
        return -1;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable CTGG_table;
    private static javax.swing.JTable SP_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextField ptgg_txt;
    private static javax.swing.JPanel ptgiam_txt;
    private javax.swing.JButton them_btn6;
    private javax.swing.JButton them_btn7;
    private javax.swing.JButton them_btn8;
    private javax.swing.JButton them_btn9;
    private javax.swing.JTextField tien_txt;
    private static javax.swing.JScrollPane tt;
    // End of variables declaration//GEN-END:variables
}
