/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Quoc Huy
 */
public class ThongTinNhanVien extends javax.swing.JPanel {

    NhanVienDTO nvdto = new NhanVienDTO();

    /**
     * Creates new form NewJPanel
     */
    public ThongTinNhanVien(NhanVienDTO nv) {
        nvdto = nv;
        initComponents();
        pn_thaydoimatkhau.setVisible(false);
        jLabel_CCCD.setText(nv.getCCCD());
        jLabel_Ten.setText(nv.getHoTenLot() + " " + nv.getTen());
        jLabel_Luong.setText(Integer.toString(nv.getLuongThang()) + "/h");
        jLabel_SDT.setText(nv.getSDT());
        String cvString = "";
        if (nv.getChucVu() == 1) {
            cvString = "Nhân viên bán hàng";
        } else {
            cvString = "Admin";
        }
        jLabel_ChucVu.setText(cvString);

        jLabel_NgaySinh.setText("1/1/2004");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_CCCD = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_idNhanVien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Ten = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_SDT = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_NgaySinh = new javax.swing.JLabel();
        jLabel_Luong = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel_ChucVu = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbn_ThayDoiMatKhau = new javax.swing.JButton();
        pn_thaydoimatkhau = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_newPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_newPassword2 = new javax.swing.JTextField();
        btn_xacNhan = new javax.swing.JButton();
        btn_dong = new javax.swing.JButton();

        setForeground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(760, 600));

        jLabel1.setBackground(new java.awt.Color(51, 255, 102));
        jLabel1.setForeground(new java.awt.Color(51, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jLabel4.setText("THÔNG TIN NHÂN VIÊN");

        jLabel_CCCD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_CCCD.setText("091204003063");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businesscard.png"))); // NOI18N
        jLabel6.setText("CCCD:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-name-32.png"))); // NOI18N
        jLabel7.setText("ID:");

        jLabel_idNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_idNhanVien.setText("1");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-name-32.png"))); // NOI18N
        jLabel9.setText("Tên:");

        jLabel_Ten.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Ten.setText("Nguyễn Quốc Huy");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/telephone.png"))); // NOI18N
        jLabel11.setText("SDT:");

        jLabel_SDT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_SDT.setText("0878955654");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calendar.png"))); // NOI18N
        jLabel13.setText("Năm Sinh");

        jLabel_NgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_NgaySinh.setText("01/01/2004");

        jLabel_Luong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Luong.setText("22đ/h");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-32.png"))); // NOI18N
        jLabel18.setText("Lương:");

        jLabel_ChucVu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_ChucVu.setText("Nhân viên bán hàng");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-job-32.png"))); // NOI18N
        jLabel20.setText("Chức vụ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel2.setText("Nhân viên là linh hồn của một cửa hàng");

        tbn_ThayDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tbn_ThayDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/password.png"))); // NOI18N
        tbn_ThayDoiMatKhau.setText("Thay đổi mật khẩu");
        tbn_ThayDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_ThayDoiMatKhauMouseClicked(evt);
            }
        });
        tbn_ThayDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ThayDoiMatKhauActionPerformed(evt);
            }
        });

        pn_thaydoimatkhau.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Mật khẩu mới");

        txt_newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newPasswordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Nhập lại mật khẩu");

        btn_xacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xacNhan.setText("Xác Nhận");
        btn_xacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xacNhanMouseClicked(evt);
            }
        });

        btn_dong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dong.setText("Đóng");
        btn_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dongMouseClicked(evt);
            }
        });
        btn_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_thaydoimatkhauLayout = new javax.swing.GroupLayout(pn_thaydoimatkhau);
        pn_thaydoimatkhau.setLayout(pn_thaydoimatkhauLayout);
        pn_thaydoimatkhauLayout.setHorizontalGroup(
            pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addComponent(btn_dong))
                .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_newPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xacNhan))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pn_thaydoimatkhauLayout.setVerticalGroup(
            pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(pn_thaydoimatkhauLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txt_newPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pn_thaydoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacNhan)
                    .addComponent(btn_dong))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_thaydoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel_ChucVu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NgaySinh)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Luong)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CCCD)
                            .addComponent(jLabel_Ten))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_idNhanVien)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbn_ThayDoiMatKhau)
                        .addGap(235, 235, 235))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CCCD)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel_idNhanVien))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel_Ten)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel_SDT))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel_NgaySinh)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel_Luong)))
                            .addComponent(pn_thaydoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel_ChucVu))
                .addGap(50, 50, 50)
                .addComponent(tbn_ThayDoiMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbn_ThayDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ThayDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbn_ThayDoiMatKhauActionPerformed

    private void txt_newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newPasswordActionPerformed

    private void btn_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dongActionPerformed

    private void tbn_ThayDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_ThayDoiMatKhauMouseClicked
        pn_thaydoimatkhau.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_tbn_ThayDoiMatKhauMouseClicked

    private void btn_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dongMouseClicked
        txt_newPassword.setText("");
        txt_newPassword2.setText("");
        pn_thaydoimatkhau.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn_dongMouseClicked

    private void btn_xacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xacNhanMouseClicked
        String p1 = txt_newPassword.getText();
        String p2 = txt_newPassword2.getText();
        if (p1.equals(p2)) {
            nvdto.setMK(p1);
            NhanVienBUS nvbus = new NhanVienBUS();
            try {
                nvbus.capNhat(nvdto);
                int messageType = JOptionPane.INFORMATION_MESSAGE;
                JOptionPane.showMessageDialog(null, "Cập nhật mật khẩu thành công!", "Thông báo", messageType);
                pn_thaydoimatkhau.setVisible(false);
                txt_newPassword.setText("");
                txt_newPassword2.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(ThongTinNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            int messageType = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(null, "Mật khẩu không trùng khớp/n Vui lòng nhập lại!", "Thông báo", messageType);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xacNhanMouseClicked

    public static void main(String[] args) {
        JFrame j = new JFrame();
        NhanVienDTO nvdto = new NhanVienDTO(15, "mk", "cccd", "nguyen quoc", " huy", "2004-12-10", "0878955654", 1, 1, 100000, 1);
        j.add(new ThongTinNhanVien(nvdto));
        j.setSize(760, 600
        );
        j.setLocationRelativeTo(null);
        j.setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dong;
    private javax.swing.JButton btn_xacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CCCD;
    private javax.swing.JLabel jLabel_ChucVu;
    private javax.swing.JLabel jLabel_Luong;
    private javax.swing.JLabel jLabel_NgaySinh;
    private javax.swing.JLabel jLabel_SDT;
    private javax.swing.JLabel jLabel_Ten;
    private javax.swing.JLabel jLabel_idNhanVien;
    private javax.swing.JPanel pn_thaydoimatkhau;
    private javax.swing.JButton tbn_ThayDoiMatKhau;
    private javax.swing.JTextField txt_newPassword;
    private javax.swing.JTextField txt_newPassword2;
    // End of variables declaration//GEN-END:variables
}
