package GUI;

import BUS.ThongKeAdminBUS;
import DTO.HoaDonDTO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NTC
 */
public class ThongKeAdminGUI extends javax.swing.JPanel {

    private final ThongKeAdminBUS thongKeAdminBUS;

    public ThongKeAdminGUI() throws SQLException {
        initComponents();
        thongKeAdminBUS = new ThongKeAdminBUS();
        ThongKeCoBan();
        panelThongKeChiTiet.setVisible(false);
    }

    public void ThongKeCoBan() {
        try {
            int soLuongSanPham = thongKeAdminBUS.demSanPham();
            lbSanpham.setText(String.valueOf(soLuongSanPham));

            int soLuongHoaDon = thongKeAdminBUS.demHoaDon();
            lbHoadon.setText(String.valueOf(soLuongHoaDon));

            int soLuongNhanVien = thongKeAdminBUS.demNhanVien();
            lbNhanvien.setText(String.valueOf(soLuongNhanVien));

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void capNhatBangHoaDon(ArrayList<HoaDonDTO> dsHoaDon) {
        // Thiết lập table
        DefaultTableModel model = (DefaultTableModel) table2.getModel();

        table2.setEnabled(false); // Chặn người dùng thao tác với table
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("ID Hóa Đơn");
        model.addColumn("ID Nhân Viên");
        model.addColumn("ID Khách Hàng");
        model.addColumn("Ngày Thành Lập");
        model.addColumn("Tổng Tiền");

        // Thêm dữ liệu từ danh sách HoaDonDTO vào model
        for (HoaDonDTO HoaDon : dsHoaDon) {
            model.addRow(new Object[]{HoaDon.getIdHoaDon(), HoaDon.getIdNhanVien(), HoaDon.getIdKhachHang(), HoaDon.getNgayLap(), HoaDon.getTongTien()});
        }

        // Tạo một DefaultTableCellRenderer và đặt thuộc tính căn giữa
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Đặt renderer cho từng cột trong JTable
        for (int i = 0; i < table2.getColumnCount(); i++) {
            table2.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        table2.setModel(model);
    }

    public static void main(String[] args) throws SQLException {
        JFrame frame = new JFrame("Thống kê Admin");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ThongKeAdminGUI thongKeAdminPanel = new ThongKeAdminGUI();
        frame.getContentPane().add(thongKeAdminPanel);
        frame.pack();
        frame.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongKeCoBan = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbHoadon = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbSanpham = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbNhanvien = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnThongKeChiTiet = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        textTongDoanhThu = new javax.swing.JLabel();
        panelThongKeChiTiet = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnXuatThongTin = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        tfBatDau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfKetThuc = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btnQuayLai = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 255, 244));
        setPreferredSize(new java.awt.Dimension(760, 470));

        panelThongKeCoBan.setBackground(new java.awt.Color(167, 255, 244));
        panelThongKeCoBan.setPreferredSize(new java.awt.Dimension(760, 470));

        jPanel9.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Số lượng hóa đơn đã bán");

        lbHoadon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbHoadon.setForeground(new java.awt.Color(255, 0, 51));
        lbHoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lbHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sản phẩm trong kho");

        lbSanpham.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSanpham.setForeground(new java.awt.Color(255, 0, 51));
        lbSanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tkSanPham.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel11.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nhanviendanghoatdong.png"))); // NOI18N

        lbNhanvien.setBackground(new java.awt.Color(255, 255, 255));
        lbNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNhanvien.setForeground(new java.awt.Color(255, 0, 51));
        lbNhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nhân viên đang hoạt động");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(lbNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("THỐNG KÊ DOANH THU");

        cbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2024", "2023", "2022", "2021", "2020" }));
        cbxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxYearActionPerformed(evt);
            }
        });

        jLabel19.setText("Năm");

        btnThongKeChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThongKeChiTiet.setText("Thống kê chi tiết");
        btnThongKeChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeChiTietActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.setInheritsPopupMenu(true);
        table.setRowHeight(40);
        jScrollPane3.setViewportView(table);

        textTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThongKeChiTiet))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongKeChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelThongKeCoBanLayout = new javax.swing.GroupLayout(panelThongKeCoBan);
        panelThongKeCoBan.setLayout(panelThongKeCoBanLayout);
        panelThongKeCoBanLayout.setHorizontalGroup(
            panelThongKeCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongKeCoBanLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelThongKeCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelThongKeCoBanLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        panelThongKeCoBanLayout.setVerticalGroup(
            panelThongKeCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeCoBanLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panelThongKeCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThongKeCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelThongKeChiTiet.setPreferredSize(new java.awt.Dimension(760, 470));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tìm kiếm mã hóa đơn");

        tfTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTimKiem.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Từ ngày");

        btnXuatThongTin.setBackground(new java.awt.Color(255, 255, 0));
        btnXuatThongTin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXuatThongTin.setText("Xuất thông tin");
        btnXuatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatThongTinActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(0, 255, 0));
        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 0, 0));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tfBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBatDau.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jLabel8.setText("Đến ngày");

        tfKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfKetThuc.setPreferredSize(new java.awt.Dimension(64, 35));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnTim)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLamMoi)
                                .addComponent(tfKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnXuatThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim)
                    .addComponent(btnLamMoi))
                .addGap(36, 36, 36)
                .addComponent(btnXuatThongTin)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table2);

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuayLai))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnQuayLai)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelThongKeChiTietLayout = new javax.swing.GroupLayout(panelThongKeChiTiet);
        panelThongKeChiTiet.setLayout(panelThongKeChiTietLayout);
        panelThongKeChiTietLayout.setHorizontalGroup(
            panelThongKeChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelThongKeChiTietLayout.setVerticalGroup(
            panelThongKeChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeChiTietLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelThongKeChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelThongKeCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelThongKeChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelThongKeCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelThongKeChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelThongKeChiTiet.getAccessibleContext().setAccessibleName("");
        panelThongKeChiTiet.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try {
            String idHoaDon = tfTimKiem.getText();
            String batDau = tfBatDau.getText();
            String ketThuc = tfKetThuc.getText();

            if (idHoaDon.isEmpty() && batDau.isEmpty() && ketThuc.isEmpty()) {
                // Hiển thị thông báo lỗi khi trường nhập liệu rỗng
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!idHoaDon.isEmpty()) {
                try {
                    int idHD = Integer.parseInt(idHoaDon);
                    ArrayList<HoaDonDTO> dsHoaDon = thongKeAdminBUS.timIdHoaDon(idHD);
                    capNhatBangHoaDon(dsHoaDon);
                    tfTimKiem.setText("");
                    tfBatDau.setText("");
                    tfKetThuc.setText("");
                    return; // Chỉ tìm kiếm theo mã hóa đơn, kết thúc sau khi tìm
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Mã hóa đơn phải là một số nguyên", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    tfTimKiem.requestFocus();
                    return;
                }
            }

            if (!batDau.isEmpty() && !ketThuc.isEmpty()) {
                // Kiểm tra định dạng ngày tháng nhập vào
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                try {
                    Date startDate = dateFormat.parse(batDau);
                    Date endDate = dateFormat.parse(ketThuc);

                    if (startDate.after(endDate)) {
                        JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được lớn hơn ngày kết thúc", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        tfBatDau.requestFocus();
                        return;
                    }
                    if (!thongKeAdminBUS.isValidDate(batDau) || !thongKeAdminBUS.isValidDate(ketThuc)) {
                        JOptionPane.showMessageDialog(this, "Ngày hoặc tháng không hợp lệ. Ngày phải từ 1-31, tháng phải từ 1-12", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    ArrayList<HoaDonDTO> dsHoaDon = thongKeAdminBUS.timHoaDonTheoNgay(batDau, ketThuc);
                    capNhatBangHoaDon(dsHoaDon);
                    tfTimKiem.setText("");
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(this, "Định dạng ngày tháng không hợp lệ. Vui lòng nhập ngày theo định dạng dd-MM-yyyy", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    tfBatDau.requestFocus();
                }
            } else if (!batDau.isEmpty() || !ketThuc.isEmpty()) {
                // Nếu chỉ có một trong hai trường ngày được điền
                JOptionPane.showMessageDialog(this, "Vui lòng điền cả ngày bắt đầu và ngày kết thúc", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi tìm kiếm hóa đơn", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        tfTimKiem.setText("");
        tfBatDau.setText("");
        tfKetThuc.setText("");

        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        try {
            panelThongKeChiTiet.setVisible(false);
            panelThongKeCoBan.setVisible(true);

            // Đặt lại giá trị mặc định của comboBox
            cbxYear.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThongKeChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeChiTietActionPerformed
        try {
            panelThongKeCoBan.setVisible(false);
            panelThongKeChiTiet.setVisible(true);

            // Đặt lại giá trị mặc định cho các textFied
            tfTimKiem.setText("");
            tfBatDau.setText("");
            tfKetThuc.setText("");
            // Đặt lại giá trị mặc định của table
            DefaultTableModel model = (DefaultTableModel) table2.getModel();
            model.setRowCount(0);
            model.setColumnCount(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThongKeChiTietActionPerformed

    private void cbxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxYearActionPerformed
        // Đặt lại giá trị mặc định của table
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        try {
            String selectedYear = (String) cbxYear.getSelectedItem();
            if ("Năm".equals(selectedYear)) {
                cbxYear.hidePopup();
                textTongDoanhThu.setVisible(false);
            } else {
                int nam = Integer.parseInt(selectedYear);
                textTongDoanhThu.setVisible(true);
                DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
                tableModel.setRowCount(1); // Đặt số hàng cho bảng
                tableModel.setColumnCount(5); // Đặt số cột cho bảng
                table.setEnabled(false); // Chặn người dùng sử dụng table

                // Lấy tổng doanh thu của từng quý trong năm và thêm dữ liệu vào tableModel
                ArrayList<Integer> doanhThuTheoQuy = thongKeAdminBUS.thongKeTheoQuy(nam);
                int tongDoanhThuNam = thongKeAdminBUS.tinhTongDoanhThuNam(nam);

                // Cập nhật tiêu đề cho các cột
//                tableModel.addColumn("Quý");
                table.getColumnModel().getColumn(0).setHeaderValue("Quý");
                table.getColumnModel().getColumn(1).setHeaderValue("Quý 1");
                table.getColumnModel().getColumn(2).setHeaderValue("Quý 2");
                table.getColumnModel().getColumn(3).setHeaderValue("Quý 3");
                table.getColumnModel().getColumn(4).setHeaderValue("Quý 4");

                // Thiết lập giá trị cho từng ô cụ thể
                table.setValueAt("Doanh Thu", 0, 0);
                table.setValueAt(doanhThuTheoQuy.get(0), 0, 1);
                table.setValueAt(doanhThuTheoQuy.get(1), 0, 2);
                table.setValueAt(doanhThuTheoQuy.get(2), 0, 3);
                table.setValueAt(doanhThuTheoQuy.get(3), 0, 4);

                // Thiết lập giá trị cho tổng doanh thu
                textTongDoanhThu.setText("Tổng doanh thu: " + String.valueOf(tongDoanhThuNam));

                // Tạo một DefaultTableCellRenderer và đặt thuộc tính căn giữa
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

                // Đặt renderer cho từng cột trong JTable
                for (int i = 0; i < table.getColumnCount(); i++) {
                    table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbxYearActionPerformed

    private void btnXuatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatThongTinActionPerformed
        //        ArrayList<HoaDonDTO> dsHoaDon = new ArrayList<>();
        //        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        //        int rowCount = model.getRowCount();
        //        for (int i = 0; i < rowCount; i++) {
            //            int idHoaDon = Integer.parseInt(model.getValueAt(i, 0).toString());
            //            int idNhanVien = Integer.parseInt(model.getValueAt(i, 1).toString());
            //            int idKhachHang = Integer.parseInt(model.getValueAt(i, 2).toString());
            //            String ngayLap = model.getValueAt(i, 3).toString();
            //            int tongTien = Integer.parseInt(model.getValueAt(i, 4).toString());
            //            HoaDonDTO hoaDon = new HoaDonDTO(idHoaDon, tongTien, 0, ngayLap, idNhanVien, idKhachHang);
            //            dsHoaDon.add(hoaDon);
            //        }
    }//GEN-LAST:event_btnXuatThongTinActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThongKeChiTiet;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXuatThongTin;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbHoadon;
    private javax.swing.JLabel lbNhanvien;
    private javax.swing.JLabel lbSanpham;
    private javax.swing.JPanel panelThongKeChiTiet;
    private javax.swing.JPanel panelThongKeCoBan;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JLabel textTongDoanhThu;
    private javax.swing.JTextField tfBatDau;
    private javax.swing.JTextField tfKetThuc;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
